version: 1.1.0

services:
  - mysql
  - php:
      version: 7.3
      
events:
  build:
    steps:
      - hello:
          type: script
          script:
            - echo "Hello world!"
            - sleep 2m
       
